version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_and_scan:
    docker:
      - image: cimg/node:20.5
    steps:
      - checkout

      # Install Node dependencies in frontend
      - node/install-packages:
          pkg-manager: npm
          app-dir: frontend

      # Run frontend tests
      - run:
          name: Run Tests
          command: |
            cd frontend
            npm test || echo "No tests yet"

      # Install official SonarScanner CLI
      - run:
          name: Install SonarScanner CLI
          command: |
            SONAR_CLI_VERSION=4.13.0.30863
            curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_CLI_VERSION-linux.zip
            # Verify itâ€™s a zip file
            file sonar-scanner-cli.zip
            unzip sonar-scanner-cli.zip
            export PATH=$PWD/sonar-scanner-$SONAR_CLI_VERSION-linux/bin:$PATH

      # Run SonarCloud scan
      - run:
          name: Run SonarCloud Scan
          command: |
            cd frontend
            sonar-scanner \
              -Dsonar.projectKey=OkoyeEmmanuel_customer-portal-react \
              -Dsonar.organization=okoyeemmanuel \
              -Dsonar.sources=./src \
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=$SONAR_TOKEN

workflows:
  main:
    jobs:
      - build_and_scan
